#  fuciona assim  
print("Olá, mundo!")
print("Esta é a primeira linha.\nEsta é a segunda linha.\nEsta é a terceira linha.")
#  funciona assim também
print("""Olá, mundo!
Esta é a primeira linha.
Esta é a segunda linha.
Esta é a terceira linha.""")                
#  funciona assim também
print('''Olá, mundo!
Esta é a primeira linha.
Esta é a segunda linha.
Esta é a terceira linha.''')                
#  funciona assim também
print("Olá, mundo!\nEsta é a primeira linha.\nEsta é a segunda linha.\nEsta é a terceira linha.")